### PR TITLE
Updated `emoji-data/emoji.json` to the latest version.

### PR DESCRIPTION
**Pull request by mnasyrov**
Updated `emoji-data/emoji.json` to the latest version. 
Fixed a emoji regex of `.scan()` method. 
Fixed `.find_by_name()` for a case when an emoji char has empty name. 
Fixed unit tests. (mroth/emoji-data-js#3)

Bench tests show performance degradation (~30% slower) of methods which scan throw all emoji list because the updated emoji-data contains 1299 emojis while the old one had 845 only.

### CODE REVIEW

**Comment by mroth** [comment]
Thanks @mnasyrov, appreciate this.  We'll need to resolve some of the complexities upstream in https://github.com/mroth/emoji_data.rb/pull/2 before we can pull this in as is here (as this library is a downstream API compatible clone of that one).

**Comment by mnasyrov** [comment]
Any update?

**Comment by jackiehluo** [comment]
Would be really great to see this merged!

**Comment by zeke** [comment]
screen shot 2016-09-24 at 8 59 15 pm

That's a lot more emoji! @mroth anything I can do to help ship this?

**Comment by mroth** [comment]
@zeke the upstream Ruby version (which this library tracks and tries to have strict API compliance with) issue is here: mroth/emoji_data.rb#2  

(The short version is we would need to have very tight controls over how we handle skin variant selectors, and rationalize how that factors into the "canonical" (skintone-less) EmojiChar versus variations.)

**Comment by mnasyrov** [comment]
@mroth Any progress on PR mroth/emoji_data.rb#2? When it is planned to be done? As I see it is a stopper for mroth/exmoji#8 as well.

**Comment by zeke** [comment]
@mroth would it be possible to just ship this as-is and push off the [aforementioned decisions about tight controls](https://github.com/mroth/emoji-data-js/pull/4#issuecomment-249694489)?

**Comment by zeke** [comment]
yolo

**Comment by mroth** [comment]
@zeke since the entire point of this library _is_ those tight controls (versus the many libraries out there that do simple translation), and a number of projects that use the library depend on it, I'm afraid not.  That said, the upstream issue shouldn't be terribly complex to resolve, someone just needs to put some time into thinking it through and testing. (I'll actually be at your office briefly next week for @maintainerati if you'd like to discuss in person in more detail!)

**Comment by zeke** [comment]
> someone just needs to put some time into thinking it through and testing

Unfortunately my Unicode expertise falls short here. Do you have any intention of picking this up again at some point? If not, that's totally understandable. I just want to have realistic expectations about the future of the project.

> I'll actually be at your office briefly next week for @maintainerati

Gah. Unfortunately I won't be there. Have a great time.

**Comment by mroth** [comment]
> Do you have any intention of picking this up again at some point? If not, that's totally understandable. I just want to have realistic expectations about the future of the project.

Hi, sorry for the slow response, I wanted to take the time to think through your question thoroughly.

* There are downstream users of this library (notably, Emojitracker itself) that have extremely exacting needs for precision, control and performance.  This means that the work of updating the library to support the evolving needs of emoji are somewhat complex, and require a bit more detail to stay useful for that.
* Emojitracker.com itself is badly in need of long-term support and maintenance beyond what I can do myself.  I have been exploring multiple routes towards trying to bring on someone else(s) to help with that (in a fair and sustainable way), but nothing is imminent.  If/when something happens there though, an obvious part of their work would be updating this library family.
* In the meantime, I would personally love to see this library (well, family of libraries) updated to support new emoji with the same degree of detail.  Emoji is an increasingly complex landscape, and I do feel there is and will be a continued need for a more exacting library than the majority of the other simple translation/search libraries out there. **It is very unlikely with my current project load/interest that I personally will be taking on writing this code myself in the near term. However, I am willing to commit a substantial amount of personal time towards _mentoring_ someone with interest towards taking that on (including video pairing, etc), because I feel like that would be much more sustainable for the long term maintainership of the library to have more folks involved.**

Hope that helps. 😬

**Comment by zeke** [comment]
> It is very unlikely with my current project load/interest that I personally will be taking on writing this code myself in the near term. However, I am willing to commit a substantial amount of personal time towards mentoring someone

cc @benedikt @dacort @bhollis @thekevinscott who have contributed to related projects in the past. Anyone interested in helping usher this forward?

**Pull request closed without merging**
